# Generated by Django 4.1 on 2022-08-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sell_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
